### ISSUE TITLE
Troubleshooting the connection between taker and maker

### ISSUE THREAD

**Issue by abhiShandy** [bitcoin-teleport/teleport-transactions#47]
Maker is rejecting connection from the taker whenever I run `do-coinswap` or `dowload-offers`

**Comment by chris-belcher** [comment]
Which network are you running it with? (options are: regtest, signet, testnet, mainnet). If you run regtest you need to run your own maker(s) too. Signet is the only network that actually has makers out there (I'm running two signet makers for now)

**Comment by hellodarkness** [comment]
I've found it works well enough on Signet.  I'm able to successfully run a maker on one machine then act as a taker on another, although the swap does sometimes fails partway through. That appears to be a Tor issue though.

As of right now, I can't see any makers online on Signet, but I do get a 'blank' orderbook instead of an error.

Running on mainnet, I can't even `download-offers`. I've been experimenting for over a week and have never been able to connect successfully.

The error I'm seeing is:

     Running `/home/ubuntu/teleport-transactions-0.1/target/debug/teleport download-offers`
thread 'main' panicked at 'network string not provided, and error connecting to bitcoin node: JsonRpc(Hyper(Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))', src/lib.rs:549:21
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
   2: teleport::download_and_display_offers::{{closure}}
             at ./lib.rs:549:21
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/future/mod.rs:91:19
   4: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:54
   5: tokio::coop::with_budget::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
   6: std::thread::local::LocalKey<T>::try_with
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/thread/local.rs:442:16
   7: std::thread::local::LocalKey<T>::with
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/thread/local.rs:418:9
   8: tokio::coop::with_budget
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5
   9: tokio::coop::budget
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
  10: tokio::park::thread::CachedParkThread::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:31
  11: tokio::runtime::enter::Enter::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/enter.rs:152:13
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/mod.rs:79:9
  13: tokio::runtime::Runtime::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/mod.rs:492:44
  14: teleport::download_and_display_offers
             at ./lib.rs:581:5
  15: teleport::main
             at ./main.rs:173:13
  16: core::ops::function::FnOnce::call_once
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
